### ISSUE TITLE
PHP error thrown browsing extensions under admin

### ISSUE THREAD

**Issue by ubuntupunk** [easysoft/zentaopms#118]
PHP version 8.1.17

```
Fatal error: Uncaught TypeError: method_exists(): Argument #1 ($object_or_class) must be of type object|string, null given in /home/user/public_html/muizenmesh.co.za/zentao/module/common/model.php:897 Stack trace: #0 /home/user/public_html/muizenmesh.co.za/zentao/module/common/model.php(897): method_exists() #1 /home/user/public_html/muizenmesh.co.za/zentao/module/common/view/header.html.php(15): commonModel::printHomeButton() #2 /home/user/public_html/muizenmesh.co.za/zentao/module/extension/view/safe.html.php(13): include('/home/user/...') #3 /home/user/public_html/muizenmesh.co.za/zentao/framework/control.class.php(385): include('/home/user/...') #4 /home/user/public_html/muizenmesh.co.za/zentao/framework/base/control.class.php(662): control->parseDefault() #5 /home/user/public_html/muizenmesh.co.za/zentao/framework/base/control.class.php(917): baseControl->parse() #6 /home/user/public_html/muizenmesh.co.za/zentao/module/extension/control.php(35): baseControl->display() #7 /home/user/public_html/muizenmesh.co.za/zentao/framework/base/router.class.php(1497): extension->__construct() #8 /home/user/public_html/muizenmesh.co.za/zentao/www/index.php(71): baseRouter->setParams() #9 {main} thrown in /home/user/public_html/muizenmesh.co.za/zentao/module/common/model.php on line 897

08:43:24 Uncaught TypeError: method_exists(): Argument #1 ($object_or_class) must be of type object|string, null given in module/common/model.php:897
Stack trace:
#0 module/common/model.php(897): method_exists()
#1 module/common/view/header.html.php(15): commonModel::printHomeButton()
#2 module/extension/view/safe.html.php(13): include('/home/user/...')
#3 framework/control.class.php(385): include('/home/user/...')
#4 framework/base/control.class.php(662): control->parseDefault()
#5 framework/base/control.class.php(917): baseControl->parse()
#6 module/extension/control.php(35): baseControl->display()
#7 framework/base/router.class.php(1497): extension->__construct()
#8 www/index.php(71): baseRouter->setParams()
#9 {main}
thrown in module/common/model.php on line 897 when visiting /zentao/www/index.php?m=extension&f=browse
```

**Comment by sy-records** [comment]
Fixed via 2bcbd46
